/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package groth16j;

import org.junit.Test;
import static org.junit.Assert.*;

public class VerifierTest {
    @Test public void testEmptyVerifier() {
        assertFalse("verifier with empty parameters should return 'false'", Verifier.verify(new byte[0], new byte[0], new byte[0]));
    }
}
